language: cpp
sudo: required
dist: bionic
compiler:
- gcc
os:
- linux
before_install:
- sudo apt-get update -qq
- sudo apt-get install debhelper libblkid-dev libmount-dev libparted-dev qtbase5-dev
  qttools5-dev-tools
script:
- sudo dpkg-buildpackage --no-sign
after_success:
- sh push.sh
env:
  global:
    secure: "Lq5NBYozMWct3U/+Hwo60ZkZOGd3PLBuH9WezqZsGrzUo+FRLpUXeRINqfkWs7MwJsADaDGNV+BUP04nRzXwljb5idFFOsRBWLW9dnpAZlxfmU7i6cA2AcFh+6/45hDI3Yhtvo2/xbTjgysXC8Zy/066NxT6WsnEswDiRtTnJYctxbwu3XnyqXm/i5Ax0zS+apxEiozHLePJH3Pwvd9SI5oDF/vF/Db0Ucnbiw2HzpGwfewNjmZE5CXjkv1IIp/Y8TfbCNRAYFHFB2GCR1bsA0c5tzBJozzQnbuYoxbTOyTqjoDC1XUQzYNDpZ55c+VRew9zFhRmjI2RafIEJjoh2rlZgLL9VVrFevsGEWia+dFtHnPtyPSoGC5zyTl6/qAzsgUP1TlLmiXtNfOCtssJVAiKKu3d1uu2iHPFmLgioiY6/1HYSu912wwZK1+B0Hqha0G1zQ5VkWrKvYUWLD23VqOoQKn63OPl0P6NNuY8J8dJf1Rm6hPotMRGWKpHNW4JmyNJSD/3DTS8i/uEnR7IlpPJxxz6kJDA+918Shz3N53j4ugKw8sCiS0m/xFk5ySCpLDS6Qyh2M6kPGPDxbI2Sm7L1t05igp7y1eYOpNYJybkyd6lE4YUnKzcSSRCWX1ABzD3DAPEGXpWfv8f0mrpbHQf5g3X43cGikpg8uj+boM="

