language: cpp
sudo: required
dist: bionic
compiler:
- gcc
os:
- linux
before_install:
- openssl aes-256-cbc -K $encrypted_f7cc8c024191_key -iv $encrypted_f7cc8c024191_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- sudo apt-get update -qq
- sudo apt-get install debhelper libblkid-dev libmount-dev libparted-dev qtbase5-dev
  qttools5-dev-tools
script:
- sh dpkg_passphrase.sh
