language: cpp
sudo: required
dist: bionic
compiler:
- gcc
os:
- linux
before_install:
- echo aaaaaaaaaaaaaaaaaaaaa
- echo ${GH_TOKEN}
- echo aaaaaaaaaaaaaaaaaaaaa
- sudo apt-get update -qq
- sudo apt-get install debhelper libblkid-dev libmount-dev libparted-dev qtbase5-dev
  qttools5-dev-tools
script:
- sudo dpkg-buildpackage --no-sign
after_success:
- sh push.sh
env:
  global:
    secure: "O3oLH20RproZwZ4SjGPYHw4tpB2LLZ+T0tHQJ5p+iwMlqv4abfd20soJ0qhAFUEx7a5M7OA56DBWSOZ/+ye6HoRG4Zcb56jNXnNPMdsSNwqq4Wfsp5KuL80jwLyxVsGucaa4N1XJkOQsOuPL2DPZh6SYvu0kDSk2MtwvL7gXwLUxE1SRO52VD5nqrxpTrrxno2tg07M01hkeZz0eO7GobhvZQhyzsV3LpDfUiPq1JLWq8ZJM+yaP5PROb+cKWKjEYfIx/DmeJ9eMP34h1hSGux7eRnZjV+p2m1GAbxEDEelGyuVZyurFE7n2mW3K6NeBtRpSw8OazdV9Ir4oxFhHzXdnGimmJlRKae5VD1eCtj/pFxdRoTjQ1daWtcXw5g3J5P6HBmBlRuu283RXEF6NTkL+QGyWmG1PEkM3xicM2fFcTMz15HQe3fUwbSCcXwqpddK8nf3FuwPGHZujKobabRfek5fKdKfH/VxJ4QJLkT2VH8K4NphC4/p/mCMm3Hqs4zaLJvE6G3cHnQKm5HPOHPRIDhIivB3w4idVfrcMvY62CbaP9uQNCB4lm/fM5I+xTVI/rf9qmvwnKFe4BRcVT9ujLAzP7jkJh20DuSR6FTNHXfFbcbU8eE2LroCyZ5Vojus5mlBetuzjXRZgUFh4Gw1xqbdcASa70lM6rrbYM/o="
