language: cpp
sudo: required
dist: bionic
compiler:
- gcc
os:
- linux
before_install:
- echo aaaaaaaaaaaaaaaaaaaaa
- echo ${GH_TOKEN}
- echo aaaaaaaaaaaaaaaaaaaaa
- sudo apt-get update -qq
- sudo apt-get install debhelper libblkid-dev libmount-dev libparted-dev qtbase5-dev
  qttools5-dev-tools
script:
- sudo dpkg-buildpackage --no-sign
after_success:
- sh push.sh
env:
  global:
    secure: "LkZyeGiUGV5BGB/DzOrbZj2MWC72a2voB0KQC7PaB60MX32wKYqf2AH+f0r4AJ+BhCqOqwkARmpDwJAPNoJMGOj2RPevCPB/0X80RT8Czj8diQBnbgDXY8WhjBw0/06zhuPt5EqB6OrI93rZhRW0+I/rxzwjUxS5iWQLMQbXZhZQOTfDxaDvxLtwqBC8S/o0dRornlqfFjjj26svJTeqAlZNMGjYBlEC9BNATf4+1NK1eXw7YELk7PJ8lOQWiAeuKuaX4z4aYw47la8bpHIRsGfi9fa6AEGJyELqzATFELaXhO5phL/XdDyYAR7EroDhb8DnF7fMjYOhhfF4cqimezwZkKwncVYjaIWFq7jmRoY0XRQA72/AfcPko5WH3RDQMHIaR7ncMYD/yN+CeZNL9UHThG1MKnB7hreXPws6FEAwFE6PcPGfZ9DyikVnHxOjZg/oMZqsfZD/0JT0+LLoCKcb0IyblEFZcrDvap/aGb3Rp/+TehmEpOI+bEcJt8mjYpTPILhajFGnUSTxdRE7ADxz6terG1b4AljAhbrjkwEhtoaXd9RnwOMc+MsM48DhsH1dJCH8WkKFiASrkZPubyM41unLe3UU7J0Ak3Qd1kgQqLqqh97a55ty01vEn7IxjmrvOBJUmWPxIVd7toWeSBwo2hj5yzh7quuGA0ssWH0="

